name: Build LaTeX document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            latexmk
            latexindent
            lacheck

      - name: Install Perl dependencies for latexindent
        run: |
          cpanm --notest YAML::Tiny File::HomeDir Unicode::GCString Log::Dispatch

      - name: Lint LaTeX source
        run: |
          lacheck main.tex

      - name: Format LaTeX source
        run: |
          latexindent -w main.tex

      - name: Build LaTeX document
        run: |
          latexmk -pdf -output-directory=out main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: out/main.pdf 